title: "Endo Medical"
description: "Market Research and Business Opportunity"
theme: jekyll-theme-minimal

nav:
  - title: "Market Research"
    url: /
  - title: "Business Opportunity"
    url: /business_opportunity.html
  - title: "Pitch Scenario"
    url: /pitch_scenario.html
